//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_Temp_Table
    {
        public int id { get; set; }
        public string Type_name { get; set; }
        public string Model { get; set; }
        public System.DateTime Purchase_date { get; set; }
        public int Invoice_no { get; set; }
        public string Vendor_name { get; set; }
        public string Asset_serial_no { get; set; }
        public int Warranty_period { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> Scrap_date { get; set; }
        public decimal Price { get; set; }
        public System.DateTime Warranty_expiry_date { get; set; }
        public string Make { get; set; }
    }
}
