//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMS_Leave_Balance_Temp
    {
        public int id { get; set; }
        public int Employee_id { get; set; }
        public Nullable<decimal> CL { get; set; }
        public Nullable<decimal> EL { get; set; }
        public Nullable<decimal> ML { get; set; }
        public Nullable<decimal> LOP { get; set; }
        public Nullable<decimal> WFH { get; set; }
    }
}
