//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incometax
    {
        public int id { get; set; }
        public int emp_id { get; set; }
        public int is_active { get; set; }
        public decimal income_tax { get; set; }
        public System.DateTime from_date { get; set; }
        public Nullable<System.DateTime> to_date { get; set; }
        public string notes { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
