//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leavebalance_sheet
    {
        public int id { get; set; }
        public int employee_id { get; set; }
        public int leavetype_id { get; set; }
        public decimal no_of_days { get; set; }
        public Nullable<decimal> actual_balance { get; set; }
    
        public virtual Leave_type Leave_type { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
