//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payslip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payslip()
        {
            this.User_Payslip = new HashSet<User_Payslip>();
        }
    
        public int id { get; set; }
        public string ctc { get; set; }
        public string basic_pay { get; set; }
        public string HRA { get; set; }
        public string FA { get; set; }
        public string MA { get; set; }
        public string CA { get; set; }
        public string PF { get; set; }
        public string MI { get; set; }
        public string ESI { get; set; }
        public string gratuity { get; set; }
        public string SA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Payslip> User_Payslip { get; set; }
    }
}
