//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_role
    {
        public int id { get; set; }
        public int employee_id { get; set; }
        public int project_id { get; set; }
        public int role_id { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public int association { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Project Project { get; set; }
        public virtual Role Role { get; set; }
    }
}
