//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timesheet
    {
        public int id { get; set; }
        public int employee_id { get; set; }
        public int work_hours { get; set; }
        public int task_id { get; set; }
        public System.DateTime work_date { get; set; }
        public int work_hour { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Task Task { get; set; }
    }
}
