//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Payslip
    {
        public int id { get; set; }
        public int emp_id { get; set; }
        public int payslip_id { get; set; }
        public System.DateTime from_date { get; set; }
        public System.DateTime to_date { get; set; }
        public int is_active { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Payslip Payslip { get; set; }
    }
}
